### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by arteeh** [eclipse-basyx/basyx-dotnet#2]
Hello, does the .NET variant of the BaSyx SDK no longer have a maintainer? And is the current version of the .NET SDK still compatible with the API's of version 1.5.1 of the Registry and Server applications?

I'm getting weird bugs where I query the registry or a server and my program just gets stuck or crashes. I've also come across situations where I request a list of shells or submodels, and I get back an incomplete list. I'm not sure if it's a bug with the BaSyx programs, this library or just an incompatibility between the two.

Whenever i've come across these bugs, I would just write my own request with HttpClient, using EnvironmentAssetAdministrationShell_V2_0 and EnvironmentSubmodel_V2_0 as the models for the JSON's I'm receiving. But doing that comes with the hassle of trying to convert it to a normal (I)AssetAdministrationShell or (I)Submodel, and on occasion this approach also leads to empty objects, as if the incoming JSON doesn't match any of the SDK's provided models.

If this project is really abandoned, then it might be better to advise .NET developers to grab the models from the Swagger API documentation (assuming those _are_ up to date) and implement the Registry/Server interactions manually.

Another option could be to instead grab libraries from the [package explorer](https://github.com/eclipse-aaspe/package-explorer), but I've noticed some differences between an AAS json produced by BaSyx and one by the AASX Explorer. For AAS version 2 I couldn't create a shell in the explorer and upload its JSON using the BaSyx AAS Server API.

PS. I also took the detour of trying to get the Java SDK working in C# using IKVM, but sadly it only supports Java 8 and lower, and BaSyx seems to rely on features in Java versions above 8. See issue: https://github.com/ikvmnet/ikvm/issues/530

**Comment by arteeh** [comment]
We've switched to the BaSyx V2 snapshots, making this SDK totally incompatible for me.

As an alternative I fed the new BaSyx OpenAPI specs (found on e.g. localhost:****/swagger-ui/index.html#/) into [Kiota](https://learn.microsoft.com/en-us/openapi/kiota/overview), a client code generator. It seems to work pretty well for me.

**Comment by StenGruener** [comment]
Same stuff here, for me it looks like this one is abandoned and probably should be de-listed from basyx pages. 
Did you check out https://github.com/aas-core-works? They have packages to serealize/deserealize JSON and XML and also to package up AASX files.

**Comment by aaronzi** [comment]
Hi @arteeh and @StenGruener,

we will update our pages in the next days to reflect which BaSyx SDKs are up-to-date and should be used. Dotnet is for now outdated but there will be potentially efforts from our side to update it to BaSyx V2 respectively AAS V3. But this will take time to get on a similar level as the BaSyx V2 Java SDK.

**Comment by arteeh** [comment]
> Did you check out https://github.com/aas-core-works? They have packages to serialize/deserialize JSON and XML and also to package up AASX files.

In an open hour session the BaSyx people suggested that library as well. However, it's not a proper substitute for us. Its scope seems to be limited to working with shells and submodels locally. API calls would have to be implemented manually. Descriptors (from registries) are also [out of scope for them](https://aas-core-works.github.io/aas-core3.0-csharp/design_decisions.html#no-aas-registry) while they are pretty important to us. I would have to implement all of that by myself.

Right now I'm feeding the openapi specs from a local BaSyx instance into Kiota, which is ([but not perfect](https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/296)) good enough for me.

Ideally I would use the specs provided by IDTA instead and generate client code from that ([but I didn't get that to work at all](https://github.com/admin-shell-io/aas-specs-api/issues/285)). In that situation our only dependency would be on the standard, and not on any implementation of it like BaSyx. That seems like the most elegant approach to writing software that interacts with an i4.0 network/factory, maybe even better than a BaSyx SDK.

And @aaronzi thank you for the status update. All questions here are answered so I'll close this.
